# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            RGV LibroBox
tagline:          LibroBox
url:              http://eduardorobles.com/Librobox-site
paginate:         1
baseurl:          /Librobox-site
author:
  name:           Eduardo Robles
  url:            https://twitter.com/rgvlibrobox
  email:          eduardorobles02@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

# This is the list of pages to incldue in the header of the website.
pages_list: {'About':'/about-lb','Archive':'/archive-lb','Connect':'/connect-lb','Feed':'/atom.xml'}
