# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            RGV LibroBox
tagline:          LibroBox
url:              http://rgvlibrobox.com
paginate:         1
baseurl:          /
author:
  name:           Eduardo Robles
  url:            https://twitter.com/rgvlibrobox
  email:          eduardorobles@rgvlibrobox.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
