# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            RGV LibroBox
tagline:          LibroBox
url:              http://eduardorobles.com/Librobox-site
paginate:         1
baseurl:          /Librobox-site
author:
  name:           Eduardo Robles
  url:            https://twitter.com/rgvlibrobox
  email:          eduardorobles02@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

# This is the list of pages to incldue in the header of the website.
pages_list: {'About':'Librobox-site/about-lb','Archive':'Librobox-site/archive-lb','Connect':'Librobox-site/connect-lb','Feed':'Librobox-site/atom.xml'}
